name: Deploy Shopping Cart API on Lamnda Function

on:
  push:
    paths:
      - "shopping_cart_api/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu/latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create zip file for Lambda Function
        run: |
          poetry install --only main --sync
          rm -rf dist/
          mkdir -p dist/lambda-package
          cp -Rv .venv/lib/python*/site-packages/* dist/lambda-package/
          cp -Rv shopping_cart_api/ dist/lambda-package/
          cd dist/lambda-package
          zip ../aws_lambda_artifact.zip -r .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:072872553653:function:shopping_cart_api \
            --zip-file fileb://dist/aws_lambda_artifact.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"